import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import ToastProvider from "./components/ToastProvider";
import UserProvider from "./components/UserProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <NavBar />
          {children}
          <ToastProvider />
        </UserProvider>
      </body>
    </html>
  );
}
